Repository scVENUS/PeekabooAV, pull requests merged in 2020-03, with the labels that each got.

#140 Original filename
  peekaboo.conf.sample
  peekaboo/config.py
  peekaboo/daemon.py
  peekaboo/ruleset/rules.py
  peekaboo/sample.py
  peekaboo/toolbox/cuckoo.py
  tests/test.py
Labels: enhancement

#142 Content disposition
  amavis/10-ask_peekaboo
  peekaboo/sample.py
  ruleset.conf.sample
  tests/test.py
Labels: enhancement

#143 Introduce FileTools and FiletoolsReport enhancement (Update)
  CHANGELOG.md
  docs/source/ruleset.rst
  peekaboo/ruleset/expressions.py
  peekaboo/ruleset/rules.py
  peekaboo/sample.py
  peekaboo/toolbox/cuckoo.py
  peekaboo/toolbox/file.py
  peekaboo/toolbox/files.py
  peekaboo/toolbox/ole.py
  ruleset.conf.sample
  tests/test-data/office/AppleDoubleencodedMacintoshfileCheckVM.xls
  tests/test-data/textfile
  tests/test.py
Labels: enhancement

#145 First 2.0 release candidate
  amavis/10-ask_peekaboo
  bin/dummy_cuckoo.py
  bin/dummy_cuckoo_submit.py
  bin/peekaboo-util.py
  bin/scan_emailed_file.py
  peekaboo.conf.sample
  peekaboo/__init__.py
  peekaboo/config.py
  peekaboo/daemon.py
  peekaboo/db.py
  peekaboo/exceptions.py
  peekaboo/locale/de/LC_MESSAGES/peekaboo.po
  peekaboo/queuing.py
  peekaboo/ruleset/__init__.py
  peekaboo/ruleset/engine.py
  peekaboo/ruleset/expressions.py
  peekaboo/ruleset/rules.py
  peekaboo/sample.py
  peekaboo/server.py
  peekaboo/toolbox/cuckoo.py
  peekaboo/toolbox/file.py
  peekaboo/toolbox/ole.py
  peekaboo/toolbox/peekabooyar.py
  peekaboo_debug.py
  ruleset.conf.sample
  setup.py
  systemd/peekaboo.service
  tests/test.py
Labels: testing

#149 Install util
  CHANGELOG.md
  README.md
  docs/source/development.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/l18n.rst
  peekaboo/__init__.py
  peekaboo/cli.py
  peekaboo_debug.py
  setup.py
Labels: documentation, enhancement

#146 Config access
  CHANGELOG.md
  dev-requirements.txt
  docs/source/config.rst
  peekaboo.conf.sample
  peekaboo/config.py
  peekaboo/daemon.py
  peekaboo/server.py
  systemd/peekaboo.service
  tests/test.py
Labels: enhancement

#150 Add dummy Cuckoo API
  bin/dummy_cuckoo_api.py
  dev-requirements.txt
  docs/source/development.rst
Labels: enhancement

#151 Update version to 2.0rc2
  peekaboo/__init__.py
Labels: documentation
